"""initial schema

Revision ID: 72af44b5ea0a
Revises: 
Create Date: 2026-06-24 18:01:34.871981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72af44b5ea0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acquisition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_acquired', sa.Integer(), nullable=True),
    sa.Column('credit_type', sa.String(length=50), nullable=True),
    sa.Column('store_name', sa.String(length=80), nullable=True),
    sa.Column('store_location', sa.String(length=180), nullable=True),
    sa.Column('from_who', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('acquisition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_acquisition_credit_type'), ['credit_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_acquisition_from_who'), ['from_who'], unique=False)
        batch_op.create_index(batch_op.f('ix_acquisition_store_location'), ['store_location'], unique=False)
        batch_op.create_index(batch_op.f('ix_acquisition_store_name'), ['store_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_acquisition_year_acquired'), ['year_acquired'], unique=False)

    op.create_table('category_counters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('closet_pieces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('year_made', sa.String(length=10), nullable=True),
    sa.Column('deaccessioned', sa.Boolean(), nullable=True),
    sa.Column('deaccessioned_notes', sa.String(length=100), nullable=True),
    sa.Column('acquisition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acquisition_id'], ['acquisition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('closet_pieces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_closet_pieces_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_closet_pieces_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_closet_pieces_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_closet_pieces_deaccessioned'), ['deaccessioned'], unique=False)
        batch_op.create_index(batch_op.f('ix_closet_pieces_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_closet_pieces_year_made'), ['year_made'], unique=False)

    op.create_table('outfits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('is_special', sa.Boolean(), nullable=False),
    sa.Column('date_worn', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=240), nullable=True),
    sa.Column('tags', sa.String(length=50), nullable=True),
    sa.Column('fk_outfits_featured_texture_piece_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_outfits_featured_texture_piece_id'], ['closet_pieces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outfits_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_outfits_date_worn'), ['date_worn'], unique=False)
        batch_op.create_index(batch_op.f('ix_outfits_tags'), ['tags'], unique=False)

    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_src', sa.String(length=400), nullable=True),
    sa.Column('alt_text', sa.String(length=200), nullable=True),
    sa.Column('media_type', sa.String(length=30), nullable=True),
    sa.Column('view', sa.String(length=10), nullable=True),
    sa.Column('outfit_id', sa.Integer(), nullable=True),
    sa.Column('closet_piece_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['closet_piece_id'], ['closet_pieces.id'], ),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_img_src'), ['img_src'], unique=True)
        batch_op.create_index(batch_op.f('ix_media_media_type'), ['media_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_view'), ['view'], unique=False)

    op.create_table('outfit_pieces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outfit_id', sa.Integer(), nullable=True),
    sa.Column('piece_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ),
    sa.ForeignKeyConstraint(['piece_id'], ['closet_pieces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outfit_pieces')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_view'))
        batch_op.drop_index(batch_op.f('ix_media_media_type'))
        batch_op.drop_index(batch_op.f('ix_media_img_src'))
        batch_op.drop_index(batch_op.f('ix_media_group_id'))

    op.drop_table('media')
    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outfits_tags'))
        batch_op.drop_index(batch_op.f('ix_outfits_date_worn'))
        batch_op.drop_index(batch_op.f('ix_outfits_code'))

    op.drop_table('outfits')
    with op.batch_alter_table('closet_pieces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_closet_pieces_year_made'))
        batch_op.drop_index(batch_op.f('ix_closet_pieces_name'))
        batch_op.drop_index(batch_op.f('ix_closet_pieces_deaccessioned'))
        batch_op.drop_index(batch_op.f('ix_closet_pieces_code'))
        batch_op.drop_index(batch_op.f('ix_closet_pieces_category'))
        batch_op.drop_index(batch_op.f('ix_closet_pieces_brand'))

    op.drop_table('closet_pieces')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('category_counters')
    with op.batch_alter_table('acquisition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_acquisition_year_acquired'))
        batch_op.drop_index(batch_op.f('ix_acquisition_store_name'))
        batch_op.drop_index(batch_op.f('ix_acquisition_store_location'))
        batch_op.drop_index(batch_op.f('ix_acquisition_from_who'))
        batch_op.drop_index(batch_op.f('ix_acquisition_credit_type'))

    op.drop_table('acquisition')
    # ### end Alembic commands ###
